apiVersion: v1
kind: ConfigMap
metadata:
  name: banking-transaction-config
  namespace: banking-transaction
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:8080"
  Back4App__BaseUrl: "https://parseapi.back4app.com"
  LOG_PATH: "/app/logs"
  SERILOG_MIN_LEVEL: "Information"
