apiVersion: v1
kind: Secret
metadata:
  name: banking-transaction-secret
  namespace: banking-transaction
type: Opaque
stringData:
  Back4App__AppId: "7HAwhsEvSnIM4AqZbmEp30vd6GlA1XHAplXanDVb"
  Back4App__RestApiKey: "VXsAdwzxpLkdr1yEY9IcXqXDNKlBRNdA9PPBHAAj"
