apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: banking-transaction-logs-pvc
  namespace: banking-transaction
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 5Gi
